services:
  - type: web
    name: depHy
    env: python
    plan: free
    branch: main
    buildCommand: "pip install --upgrade pip==23.3.1 setuptools==68.2.2 wheel==0.41.2 && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: PYTHONPATH
        value: "."
